#lsi: true
safe: true
source: [/sverres.github.io]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

#name: Emanuel Desperados
#author:
#  name: Office of the Chief Technology Officer
#  url: http://octo.dc.gov
#theme: minima